import {
    DocumentDuplicateIcon,
    DocumentTextIcon,
    EyeIcon,
    CodeIcon,
    PencilAltIcon,
    SupportIcon,
    TerminalIcon,
    CubeIcon,
    NewspaperIcon,
    PhotographIcon,
    TranslateIcon,
    PuzzleIcon,
    GlobeAltIcon,
    CogIcon,
    UsersIcon,
    ExternalLinkIcon,
    StatusOnlineIcon,
    CalendarIcon,
    SearchCircleIcon,
    DatabaseIcon
  } from '@heroicons/react/outline'

export default {
    DocumentDuplicateIcon,
    DocumentTextIcon,
    EyeIcon,
    CodeIcon,
    PencilAltIcon,
    SupportIcon,
    TerminalIcon,
    CubeIcon,
    NewspaperIcon,
    PhotographIcon,
    TranslateIcon,
    PuzzleIcon,
    GlobeAltIcon,
    CogIcon,
    UsersIcon,
    ExternalLinkIcon,
    StatusOnlineIcon,
    CalendarIcon,
    SearchCircleIcon,
    DatabaseIcon
}